project.version=0.6.0+1.19.4
project.java=17
project.build-java=21
project.minecraft=1.19.4
project.enabled-loaders=fabric,forge
project.catalog-name=libsMc1194
project.catalog-coordinate=com.iamkaf.platform:mc-1.19.4:1.19.4-SNAPSHOT

mixin.compat.common=JAVA_17
mixin.compat.fabric=JAVA_17
mixin.compat.forge=JAVA_17
mixin.compat.neoforge=JAVA_17

mod.minecraft-range=[1.19.4, 1.20)
mod.fabric-range=>=1.19.4
mod.forge-loader-range=[45,)

dependencies.modrinth.required=amber
dependencies.curseforge.required=amber-lib
