org.gradle.caching=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

project.group=com.iamkaf.arcanearmory
project.plugins=3.0-SNAPSHOT

mod.name=Arcane Armory
mod.authors=iamkaf
mod.id=arcanearmory
mod.license=MIT
mod.credits=
mod.description=Material-driven tools, armor, ores, and arcane alloys.

publish.dry-run=true
publish.curseforge.id=NOT_PUBLISHABLE
publish.modrinth.id=BwvGX21P
publish.release-type=alpha
publish.game-versions=auto
environments.client=required
environments.server=required

mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_21
mixin.compat.neoforge=JAVA_21
